name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    timeout-minutes: 30
    needs: [package, test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: my-artifact
      
      - name: Deploy 
        run: |
          mkdir release
          cp target/release/khonsulabs-projects release/
          cp -r static/ release/
          cp -r templates release/ 
          rsync -avz release/ projects@khonsulabs.com:projects/
          ssh projects@khonsulabs.com sudo /usr/bin/systemctl restart projects.service