name: Deploy

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Rust
        uses: hecrj/setup-rust-action@v1

      - name: Build tests
        run: |
          cargo test --all-features --no-run

      - name: Run unit tests
        run: |
          cargo test --all-features
        env:
          RUST_BACKTRACE: 1

  package:
    runs-on: ubuntu-latest
    environment: Production
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Rust
        uses: hecrj/setup-rust-action@v1

      - name: Build 
        run: |
          cargo build --bin khonsulabs-projects --release

      - uses: actions/upload-artifact@v2
        with:
          name: khonsulabs-projects
          path: target/release/khonsulabs-projects

  deploy:
    runs-on: ubuntu-latest
    environment: Production
    timeout-minutes: 30
    needs: [package, test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: khonsulabs-projects
      
      - name: Gather artifacts 
        run: |
          mkdir release
          mv khonsulabs-projects release/
          cp -r static/ release/
          cp -r templates release/ 

      - name: Configure SSH 
        run: |
          mkdir ~/.ssh
          chmod 0700 ~/.ssh
          echo "$PROJECTS_SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 0600 ~/.ssh/deploy_key
          ssh-keyscan -H khonsulabs.com ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          
      - name: Deploy
        run: |
          rsync -avz -e "ssh -i ~/.ssh/deploy_key" release/ projects@khonsulabs.com:projects/
          ssh -i ~/.ssh/deploy_key projects@khonsulabs.com sudo /usr/bin/systemctl restart projects.service
        env:
          PROJECTS_SSH_PRIVATE_KEY: ${{ secrets.PROJECTS_SSH_PRIVATE_KEY }}